services:
  - type: web
    name: hello-world-app
    runtime: image
    image:
      url: ghcr.io/shaharido1/photo-album-project:latest
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: false
    healthCheckPath: /healthz
